package com.dreamfirestudios.dreamCore.DreamfirePlayer;

import com.dreamfirestudios.dreamCore.DreamfireEvents.EventCheckUtils;
import org.bukkit.event.block.BlockDispenseArmorEvent;

public enum DreamfirePlayerAction {
    PlayerCommand,
    EntityPortalEnterEvent,
    EntityPlaceEvent,
    EntityPickupItemEvent,
    EntityMountEvent,
    EntityKnockbackEvent,
    EntityKnockbackByEntityEvent,
    EntityInteractEvent,
    EntityExhaustionEvent,
    EntityEnterLoveModeEvent,
    EntityEnterBlockEvent,
    EntityDropItemEvent,
    EntityDismountEvent,
    EntityDeathEvent,
    EntityDamageByEntityEvent,
    EntityDamageByBlockEvent,
    EntityCreatePortalEvent,
    EntityCombustEvent,
    EntityCombustByEntityEvent,
    EntityCombustByBlockEvent,
    EntityChangeBlockEvent,
    EntityBreedEvent,
    EntityBreakDoorEvent,
    EnderDragonChangePhaseEvent,
    CreeperPowerEvent,
    PlayerMove,
    PlayerRotate,
    PlayerSounds,
    PlayerTitle,
    PlayerActionBar,
    PlayerBlockMask,
    PlayerBossBar,
    PlayerCamPath,
    PlayerEntityMask,
    PlayerLocationLimiter,
    PlayerDreamfirePrompt,
    BellRingEvent,
    BlockBreakEvent,
    BlockCanBuildEvent,
    BlockCookEvent,
    BlockDamage,
    BlockDispenseEvent,
    BlockDispenseArmorEvent,
    BlockDispenseLootEvent,
    BlockDropItemEvent,
    BlockExplodeEvent,
    BlockFadeEvent,
    BlockFertilizeEvent,
    BlockFormEvent,
    BlockGrowEvent,
    BlockIgniteEvent,
    BlockMultiPlaceEvent,
    BlockPhysicsEvent,
    BlockPistonEvent,
    BlockPistonExtendEvent,
    BlockPistonRetractEvent,
    BlockPlaceEvent,
    BlockReceiveGame,
    BlockShearEntityEvent,
    BlockSpreadEvent,
    CrafterCraftEvent,
    EntityBlockFormEvent,
    FluidLevelChangeEvent,
    LeavesDecayEvent,
    MoistureChangeEvent,
    NotePlayEvent,
    SculkBloomEvent,
    SignChangeEvent,
    SpongeAbsorbEvent,
    TNTPrimeEvent,
    EnchantItemEvent,
    BlockDamageAbortEvent,
    PrepareItemEnchantEvent,
    AreaEffectCloudApplyEvent,
    BatToggleSleepEvent,
    CreatureSpawnEvent
}



