package com.dreamfirestudios.dreamCore.DreamfireBossBar;

import com.dreamfirestudios.dreamCore.DreamfireChat.DreamfireMessage;
import net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer;
import org.bukkit.boss.BarColor;
import org.bukkit.boss.BarStyle;
import org.bukkit.boss.BossBar;
import org.bukkit.entity.Player;

import java.util.function.Function;

public record DreamfireBossBarData(BarColor barColor, BarStyle barStyle, double barProgress, Function<Player, String> messageProvider) {
    /**
     * Displays the boss bar data for a specific player.
     * This method updates the title, color, style, and progress of the boss bar.
     *
     * @param bossBar The boss bar to be updated.
     * @param player  The player for whom the boss bar data is displayed.
     */
    public void DisplayBarData(BossBar bossBar, Player player){
        if (bossBar == null) throw new IllegalArgumentException("BossBar cannot be null");
        if (player == null) throw new IllegalArgumentException("Player cannot be null");
        var barTitle = messageProvider.apply(player);
        if (barTitle == null || barTitle.isEmpty()) throw new IllegalArgumentException("Bar title generated by the message provider cannot be null or empty");
        bossBar.setTitle(PlainTextComponentSerializer.plainText().serialize(DreamfireMessage.formatMessage(barTitle, player)));
        bossBar.setColor(barColor);
        bossBar.setStyle(barStyle);
        bossBar.setProgress(Math.max(0, Math.min(1, barProgress)));
    }
}
